#
# Author: Hayden Stainsby <hds@caffeineconceps.com>
# Last serious edit: 2012-11-09
#


MPICC = mpicc
MKDIR = mkdir -p

PRJDIR = $(CURDIR)
SRCDIR = $(PRJDIR)/src
OBJDIR = $(PRJDIR)/obj
BINDIR = $(PRJDIR)/bin

